# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x0breplication\"E\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x10\n\x08priority\x18\x03 \x01(\x05\x12\x11\n\thop_count\x18\x04 \x01(\x05\"$\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04info\x18\x02 \x01(\t\"!\n\x0cStealRequest\x12\x11\n\tmax_tasks\x18\x01 \x01(\x05\",\n\x08TaskList\x12 \n\x05tasks\x18\x01 \x03(\x0b\x32\x11.replication.Task\"\x0f\n\rStatusRequest\"A\n\x06Status\x12\x11\n\tqueue_len\x18\x01 \x01(\x05\x12\x11\n\tcpu_usage\x18\x02 \x01(\x02\x12\x11\n\tmem_usage\x18\x03 \x01(\x02\x32\xbf\x01\n\x0bTaskService\x12\x32\n\x0b\x45nqueueTask\x12\x11.replication.Task\x1a\x10.replication.Ack\x12>\n\nStealTasks\x12\x19.replication.StealRequest\x1a\x15.replication.TaskList\x12<\n\tGetStatus\x12\x1a.replication.StatusRequest\x1a\x13.replication.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASK']._serialized_start=27
  _globals['_TASK']._serialized_end=96
  _globals['_ACK']._serialized_start=98
  _globals['_ACK']._serialized_end=134
  _globals['_STEALREQUEST']._serialized_start=136
  _globals['_STEALREQUEST']._serialized_end=169
  _globals['_TASKLIST']._serialized_start=171
  _globals['_TASKLIST']._serialized_end=215
  _globals['_STATUSREQUEST']._serialized_start=217
  _globals['_STATUSREQUEST']._serialized_end=232
  _globals['_STATUS']._serialized_start=234
  _globals['_STATUS']._serialized_end=299
  _globals['_TASKSERVICE']._serialized_start=302
  _globals['_TASKSERVICE']._serialized_end=493
# @@protoc_insertion_point(module_scope)
